zeppelin:
    image: apache/zeppelin:0.9.0
    container_name: zeppelin
    environment:
        ZEPPELIN_PORT: 8080
        ZEPPELIN_JAVA_OPTS: >-
            -Dspark.driver.memory=6g
            -Dspark.executor.memory=6g
        MASTER: local[*]
    ports:
        - 8080:8080
        - 4040:4040
    volumes:
        - ./data:/usr/zeppelin/data
        - ./notebooks:/zeppelin/notebook/ads